In [1]:
import numpy as np
import matplotlib.pyplot as plt
import classy
from classy import Class

In [2]:
params_lcdm = {'output': 'mPk, dTk', 
               'P_k_max_1/Mpc': 3.0, 
               'non_linear': 'halofit', 
               'z_max_pk': '0.5',
               'Omega_cdm': '0.25',
               'Omega_b': '0.05',
               'background_verbose': '2',
               'H0': '67.32'}
lcdm = Class()
lcdm.set(params_lcdm)
lcdm.compute()

In [3]:
cosmo1=Class()
cosmo1.set ({'output':'mPk, dTk','P_k_max_1/Mpc':3.0, 'Omega_Lambda' : 0., 'non_linear':'halofit','z_max_pk':'0.5',
               'Omega_cdm':'0.25' ,'Omega_b':'0.05', 'background_verbose': '2', 'H0': '67.32',
            'fluid_equation_of_state': 'CLP', 'w0_fld' : -0.99, 'wa_fld' : 0., 'e_pi' : 0.5, 'f_pi' : 8.0,
            'log10ceff2' : -5.0, 'log10g_pi' : 10.0, 'use_ppf' : 'no', 'gauge' : 'newtonian'})
cosmo1.compute()

In [4]:
params_ewcdm = {'output': 'mPk, dTk',
                'P_k_max_1/Mpc': 3.0,
                'Omega_Lambda': 0.,
                'non_linear': 'halofit',
                'modes': 's', #
                'A_s': 2.3e-9, #
                'n_s': 0.9616, #
                'z_max_pk': '0.5',
                'Omega_cdm': '0.25',
                'Omega_b': '0.05',
                'background_verbose': '2',
                'H0': '67.32',
                'fluid_equation_of_state': 'CLP',
                'w0_fld': -0.99,
                'wa_fld': 0.,
                'e_pi': 0., #from 0.5 to 0
                'f_pi': 0., #from 8.0 to 0
                'log10ceff2': -5.0,
                'log10g_pi': 10.0,
                'use_ppf': 'no',
                'gauge': 'newtonian'}
ewcdm = Class()
ewcdm.set(params_ewcdm)
ewcdm.compute()

In [ ]:
weyl_ew = ewcdm.get_Weyl_pk_and_k_and_z()[0]

In [ ]:
weyl_lcdm = lcdm.get_Weyl_pk_and_k_and_z(nonlinear = False)[0]

In [5]:
pk_ew = ewcdm.get_pk_and_k_and_z(nonlinear=False)[0][:,0] # z = 0.24
pk_k_ew = ewcdm.get_pk_and_k_and_z(nonlinear=False)[1]

In [8]:
pk_ew = ewcdm.get_pk_and_k_and_z(nonlinear=False)[0][:,3] # z = 0.0
pk_k_ew = ewcdm.get_pk_and_k_and_z(nonlinear=False)[1]

In [7]:
pk_ew_z = ewcdm.get_pk_and_k_and_z(nonlinear=False)[2]
pk_ew_z

array([0.24343151, 0.12307202, 0.01379159, 0.        ])

In [9]:
pk_ew

array([1.90842151e+02, 2.32104269e+02, 3.19831524e+02, 3.70737892e+02,
       4.48686981e+02, 5.59406560e+02, 7.00262453e+02, 8.76368399e+02,
       1.09611104e+03, 1.36935942e+03, 1.70792150e+03, 2.13102078e+03,
       2.65859644e+03, 3.31668362e+03, 4.13648558e+03, 5.15708614e+03,
       6.42505685e+03, 7.99843278e+03, 9.94538319e+03, 1.23460680e+04,
       1.52921147e+04, 1.88842594e+04, 2.32294188e+04, 2.84272975e+04,
       3.45547138e+04, 4.16414889e+04, 4.96358812e+04, 5.83611591e+04,
       6.74640352e+04, 7.63573193e+04, 8.41636755e+04, 8.97019543e+04,
       9.15215016e+04, 8.82288521e+04, 7.92364910e+04, 6.59231925e+04,
       5.27582866e+04, 4.52710009e+04, 4.17079909e+04, 3.95504559e+04,
       3.79539005e+04, 3.65717826e+04, 3.52299693e+04, 3.38343831e+04,
       3.23428074e+04, 3.07425796e+04, 2.90499063e+04, 2.72969733e+04,
       2.55282973e+04, 2.37981400e+04, 2.21564735e+04, 2.06507802e+04,
       1.93163833e+04, 1.81753250e+04, 1.72320038e+04, 1.64746807e+04,
      

In [10]:
pk_k_ew

array([6.93296453e-06, 8.72808523e-06, 1.09880083e-05, 1.38330829e-05,
       1.74148195e-05, 2.19239589e-05, 2.76006289e-05, 3.47471331e-05,
       4.37440489e-05, 5.50704948e-05, 6.93296453e-05, 8.72808523e-05,
       1.09880083e-04, 1.38330829e-04, 1.74148195e-04, 2.19239589e-04,
       2.76006289e-04, 3.47471331e-04, 4.37440489e-04, 5.50704948e-04,
       6.93296453e-04, 8.72808523e-04, 1.09880083e-03, 1.38330829e-03,
       1.74148195e-03, 2.19239589e-03, 2.76006289e-03, 3.47471331e-03,
       4.37440489e-03, 5.50704948e-03, 6.93296453e-03, 8.72808523e-03,
       1.09880083e-02, 1.38330828e-02, 1.74147511e-02, 2.19139354e-02,
       2.72495800e-02, 3.18193966e-02, 3.51215830e-02, 3.78332103e-02,
       4.02488981e-02, 4.24990158e-02, 4.46521634e-02, 4.67493024e-02,
       4.88172542e-02, 5.08748746e-02, 5.29362026e-02, 5.50122049e-02,
       5.71118078e-02, 5.92425390e-02, 6.14109452e-02, 6.36228724e-02,
       6.58836603e-02, 6.81982799e-02, 7.05714327e-02, 7.30076242e-02,
      